name: Remove obsolete branches

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/remove-obsolete-branches.yml"

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Delete obsolete branches
        run: |
          git push origin --delete dev
          git push origin --delete fix-aovlist-issue-9
          git push origin --delete cran-readiness-superb-removal
